title: GitHub Pages Test Website
author: Krista R
email: kris.ro.rob@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Following the tutorial for creating a website through GitHub Pages, this is my example site.

theme: minima

# social links
twitter_username: ro_krista # DO NOT include the @ character, or else the build will fail!
github_username:  Kris-Rose # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
